### ISSUE TITLE
propTypes and defaultValues when spread (...) do not show-up on the PropsTable

### ISSUE THREAD

**Issue by Kivylius** [doczjs/docz#1411] opened 2020-03-05 22:18 UTC
## Bug Report

Proptypes or defaultProps that are spread do not shopup on PropTable.

**To Reproduce**

I've created a sample app that you can test this behavour. One single button with single mdx file.

https://github.com/kivylius/docz-no-spread

**Expected behavior**

The props and default values to showup on docz.

**Environment**

- docz version: [e.g. v2.2.0, v2.3.0-alpha.13]
- OS: [OSX 10.13.4]
- Node/npm version: [Node 10]

**Additional context/Screenshots**

<img width="1286" alt="Screenshot 2020-03-05 at 22 12 34" src="https://user-images.githubusercontent.com/1041335/76030914-8ef86800-5f2e-11ea-9b31-3d532d8abbf5.png">

**SideNote**

if importing with this syntax, the code never compiles and crashes. In the mdx or even an component.

```
import test from '..';
```

Even tho this is a valid import in react.

**Comment by mickaelzhang** [comment] 2020-03-06 09:02
It's an issue with `docgen` itself (the lib that we use to get the prop type).
See for more info https://github.com/styleguidist/react-styleguidist/issues/792

**Comment by Kivylius** [comment] 2020-03-06 10:40
Thanks for the reply, but your links points to https://github.com/reactjs/react-docgen/pull/282 which seems to fix the issue 2 years ago. Are we not using that versions?

**Comment by mickaelzhang** [comment] 2020-03-06 13:47
The issue is not resolved from what I know, you can check some issue on here  https://github.com/reactjs/react-docgen/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+spread

**Comment by mickaelzhang** [comment] 2020-03-16 17:37
@Kivylius I'll close this issue for now but feel free to re-open if you think I didn't answer your question well! :)

**Closed by mickaelzhang** 2020-03-16 17:37 UTC

**Comment by jasongaare** [comment] 2020-08-20 18:53
I am seeing a similar issue, where the proptypes seem to be ignore or swallowed up when using a spread. For instance, we have an `IconButton` which composes two other components, which have fully-fleshed out proptypes.

```
IconButton.propTypes = {
  ...Button.propTypes,
  ...Icon.propTypes,
};
```

but this results in nothing displayed by `<PropTypes of={IconButton} />`

having this functionality would be very helpful in reducing code duplication...
