### ISSUE TITLE
Invalid hook call

### ISSUE THREAD

**Issue by mauriciord** [doczjs/docz#837] opened 2019-04-27 20:22 UTC
## Bug Report

**Describe the bug**

I installed following the Docs of DOCZ, but when i run `docz dev`, it successfully open localhost:3000, but outputs me this error:
```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

```

**Expected behavior**

*Expected to see my index.mdx render successful*

**Environment**

* OS: [e.g. OSX 10.13.4, Windows 10]
* Node/npm version: [e.g. Node 8/npm 5]

**Additional context/Screenshots**
<img width="1058" alt="Screen Shot 2019-04-27 at 17 14 16" src="https://user-images.githubusercontent.com/1128701/56854682-e0989500-6910-11e9-89b0-7a10e59a98c4.png">

My stack versions:
```json
     "react": "16.8.3",
    "react-art": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-native": "0.59.5",
    "react-native-web": "^0.11.2"

    "docz": "^1.0.4",
    "typescript": "^3.3.4000",
```

My doczrc.js:
```js
export default {
  title: 'Docz Typescript',
  codeSandbox: false,
  typescript: true,
  native: true,
}
```

**Comment by johntran** [comment] 2019-04-29 03:57
Looks to be a duplicate of: https://github.com/pedronauck/docz/issues/707

**Closed** 2019-09-29 17:36 UTC
