### ISSUE TITLE
Not able to access static assets

### ISSUE THREAD

**Issue by IsAmrish** [doczjs/docz#1119] opened 2019-09-19 14:23 UTC
## Question

I was trying to access the static assets from localhost but I am unable to do. I tried to add to use  `public` key in doczrc.js file by following this issue https://github.com/doczjs/docz/issues/502. But I could not access my static assets in the browser.

Is there anything that I am missing?

Thanks

**Comment by rakannimer** [comment] 2019-09-22 18:53
You're trying to access static assets from your JS code not from an mdx file right ? 

If yes, it looks like there's an issue with using static assets from jsx code. 

We'll hopefully fix that before the official v2 is released.

**Comment by rakannimer** [comment] 2019-09-29 14:23
Hey this was fixed starting from [version 2.0.0-rc.44](https://github.com/doczjs/docz/releases/tag/v2.0.0-rc.44).

You can check an example of using images in docz from mdx and jsx files here : https://github.com/doczjs/docz/tree/master/examples/images

You can also set the `public` field in doczrc.js to use a different directory for your public assets .

**Comment by rakannimer** [comment] 2019-10-30 14:32
Closing this as it should be fixed. Please feel free to re-open if a regression occurs.

**Closed by rakannimer** 2019-10-30 14:32 UTC
Labels: bug, fixed, pending-user-response, v2
