### ISSUE TITLE
docz getting started guide - npm run docz:dev will fail if yarn is not installed globally

### ISSUE THREAD

**Issue by brauliodiez** [doczjs/docz#1015] opened 2019-08-21 08:09 UTC
## Bug Report

I have follown your guide on a clean machine, it had only npm installed no yarn, realized that:

- I could execute the npm install no problem.
- When I executed:

```bash
npm run docz:dev
```
An error was thrown:

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
```
After installing yarn globally:
```bash
npm install yarn -g
```
It started to  work fine. I think it would be a good idea to update the docs in order to reflect that _yarn_ is a must if we want to run the project.

**Environment**

* OS: OSX 10.14.5
* Node/npm version: Node 10.14.2

**Comment by maccuaa** [comment] 2019-08-21 12:25
duplicate of #959

**Comment by jesperorb** [comment] 2019-10-06 10:26
Follow this issue in https://github.com/doczjs/docz/issues/959 instead

**Closed by jesperorb** 2019-10-06 10:26 UTC
Labels: docs, duplicate, enhancement, v2
