### ISSUE TITLE
SyntaxError: Expected corresponding JSX closing tag

### ISSUE THREAD

**Issue by lparedesl** [doczjs/docz#1691] opened 2022-01-12 02:45 UTC
Getting `SyntaxError: Expected corresponding JSX closing tag` error when using any component with children inside the `Playground` component.

Using components that self close, for example `<MyComponent />` works fine.

Here is a sample with the error. Please click on Components > Alert on the left menu.

https://codesandbox.io/s/docz-example-xj522

Thanks

**Comment by panvourtsis** [comment] 2022-01-13 08:04
i got an update on this @lparedesl. Following on the `mdx-js` lib issues I found [this](https://github.com/frontarm/mdx-util/issues/43) which makes me think.

if you try and replace them it works. That doesn't actually solve this but I think is the `mdx-js` library problem working with docz

```
<Playground>
  &lt;Alert kind="info"&gt;Some message&lt;/Alert&gt; &lt;Alert
  kind="positive"&gt;Some message&lt;/Alert&gt; &lt;Alert
  kind="negative"&gt;Some message&lt;/Alert&gt; &lt;Alert kind="warning"&gt;Some
  message&lt;/Alert&gt;
</Playground>
```

**Comment by panvourtsis** [comment] 2022-01-13 14:39
today i used the example below to add typescript support and all and it worked. 

https://codesandbox.io/s/9pucf

If you delete the yarn.lock though and rerun the yarn install it will again break.

**Comment by tanbowensg** [comment] 2022-01-18 06:46
same problem

**Comment by lparedesl** [comment] 2022-01-18 10:38
> today i used the example below to add typescript support and all and it worked.
> 
> https://codesandbox.io/s/9pucf
> 
> If you delete the yarn.lock though and rerun the yarn install it will again break.

Thank you. I will try that

**Comment by bartlomiej-kochanowicz** [comment] 2022-01-19 12:40
any update?

**Comment by iandeherdt** [comment] 2022-01-19 12:52
Same issue

**Comment by panvourtsis** [comment] 2022-01-19 12:52
couldn't find what caused it.

**Comment by gmonte** [comment] 2022-01-21 21:34
Same issue here.

![Screen Shot 2022-01-21 at 18 30 33](https://user-images.githubusercontent.com/2854922/150602832-91cc3708-e027-4be6-afa0-33ebfffcdba0.png)
![Screen Shot 2022-01-21 at 18 31 13](https://user-images.githubusercontent.com/2854922/150602844-b5cd81f2-f698-4719-a4eb-a91fd284d7a3.png)
![Screen Shot 2022-01-21 at 18 30 52](https://user-images.githubusercontent.com/2854922/150602849-8b88f97e-59c3-41b0-bee6-af8186b432db.png)
![Screen Shot 2022-01-21 at 18 31 26](https://user-images.githubusercontent.com/2854922/150602851-6072a731-e12d-4888-844a-26fd34a11020.png)

I have the same behavior when I use with/without a function body. It is working just with auto-closing tags.

**Comment by Elgeneinar** [comment] 2022-01-24 11:56
Same issue here. For me it seems to be cutting out the first ending tag, so 
```
<Playground>
<div> **</div>**
<p> </p>
</Playground>
```

becomes
```
<Playground>
<div>
<p> </p>
</Playground>
```

**Comment by adbayb** [comment] 2022-01-28 16:05
After investigation, it seems that forcing (through yarn resolution or whatever) the downgrade of the package `@babel/traverse` to **v7.16.7** (or `@babel/core` to v7.16.7) solves the issue. 
The regression was introduced for versions greater or equal to `v7.16.8`.

**Comment by nicolo-ribaudo** [comment] 2022-01-29 07:59
Hi! Babel maintainer here.

I'd be happy to help figure out if this is a Babel bug, or if it's a bug somewhere else that was hidden in this specific circumstance and unveiled by that Babel update.

Does docz use any Babel ugin to transform `<Playground>` tags to `<React.Fragment>` tags? I only found https://github.com/doczjs/docz/tree/main/other-packages/babel-plugin-export-metadata but it looks unrelated.

**Comment by adbayb** [comment] 2022-01-31 07:42
Hello @nicolo-ribaudo 👋 ,
First of all, thanks for your time and involvement 🙏 . 

I've mentioned the https://github.com/babel/babel/pull/14105 since the issue starts to appear from `@babel/traverse@v7.16.8` and above (same issue also with `@babel/traverse@7.16.10`). 
From the changelog, I can see that the only change introduced since was https://github.com/babel/babel/pull/14105. 

> Does docz use any custom Babel plugin to transform <Playground> tags?

I'm not an active maintainer of Docz but from what I see Docz is using the [react-live](https://github.com/doczjs/docz/blob/d2ab7c348376d15beb9b7d21ee6b162cd2c9dd1f/core/gatsby-theme-docz/src/components/Playground/index.js#L5) dependency to manage live previews.

Maybe the maintainers @pedronauck / @renatobenks can confirm.

**Comment by nicolo-ribaudo** [comment] 2022-01-31 15:53
After a very long debug session (it took a few hours because I was not familiar with the project :grimacing:), I came to the conclusion that:
- It's true that this behavior changed because of https://github.com/babel/babel/pull/14105
- This is a docz bug, which was previously working because it met the exact condition in which the Babel bug that it was accidentally relying on was happening.

---

**What is the fixed Babel bug exactly?**

Babel has a few utility methods to control how the AST is traversed. One of them if `path.stop()`, whose goal is to _enterly stop the current traversal_. You can read its documentation in our [semi-official plugins handbook](https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md#stopping-traversal).

However, in some circumstances it only prevented _part_ of the remaining nodes from being traversed, rather than all of them. We fixed this bug, and now `path.stop()` behaves properly.

---

**What is the docz bug?**

docz has some code to remove the `<Playground>...</Playground>` tags, transforming
```js
<Playground>
  <Alert>Some text here</Alert>
</Playground>
```
into
```js
  <Alert>Some text here</Alert>
```

This is the utility function that should do that transformation:
https://github.com/doczjs/docz/blob/259898c25838c052048bd81277d0d74d0ee5c1e2/core/docz-utils/src/jsx.ts#L13-L18

For completeness, here is the `codeFromNode` function:
https://github.com/doczjs/docz/blob/259898c25838c052048bd81277d0d74d0ee5c1e2/core/docz-utils/src/ast.ts#L7-L28

`codeFromNode` takes a "condition" function, and returns a function that, when given the input code, returns a portion of the code whose AST matches the condition.

`const open = codeFromNode(p => p.isJSXOpeningElement()); open(code)` returns the the code of something that matches `p.isJSXOpeningElement()`.

In our example above, both `<Playground>` and `<Alert>` match that condition: which one does it return? If we look at the `valueFromTraverse` implementation, it:
- parses the input source code
- traverses it with `@babel/traverse` (Babel uses a DFS traversal, and when using the `enter` visitor it's in visits the node in pre-order).
- when it finds a node that matches the condition, it stores it's value and calls `path.stop()` to stop the traversal.

Calling `path.stop()` as soon as something matches the condition means that it returns the _first_ node that matches it. When looking for a `JSXOpeningElement` it thus returns `<Playground>`, while when looking for a `JSXClosingElement` it's `</Alert>`.

_(It might help looking at [the AST for my example](https://astexplorer.net/#/gist/2fb4e9e26a3b09e9aafc247e7d70456d/4d3d7a622be7edc67de3ea09c93943b2313bcd05), remembering that Babel traverses nodes in "source code order": when it comes to JSX, it first traverses the opening tag, then the children and then the closing tag.)_

After getting `<Playground>` and `</Alert>`, `removeTags` removes them from the input code.

We were "lucky" before because `path.stop()` didn't work properly in that case, so it didn't stop the traversal when it found a closing tag but continued normally (reaching `</Playground>` at the end of the traversal).

---

**My suggested fix**

Rather than finding an opening and a closing tag separately, I suggest getting them at the same time. Also, the current `.replace`-based approach is quite fragile. For example (even before the `@babel/traverse` fix), this didn't work:
```js
<Playground>
  This is followed by a comment! { /* </Playground> */ }
  <Alert>Some text here</Alert>
</Playground>
```
because by replacing `<Playground>` and `</Playground>` with an empty string you get:
```js
  This is followed by a comment! { /*  */ }
  <Alert>Some text here</Alert>
</Playground>
```

I suggest to rewrite `removeTags` like this:
```ts
const getTagContentsRange = valueFromTraverse(
  p => p.isJSXElement(),
  ({ node }) => {
    if (!node.closingElement) {
      // if the JSX element doesn't have a closingElement, it's because it's self-closed
      // and thus does not have any content: <Playground />
      return [0, 0];
    }
    return [node.openingElement.end, node.closingElement.start];
  }
);

export const removeTags = (code: string) => { 
  const [start, end] = getTagContentsRange(code);
  return code.slice(start, end);
};
```
by doing so we get the start/end location of the contents of the first JSX tag, which should be safe.

**Comment by nicolo-ribaudo** [comment] 2022-01-31 19:19
I ended up creating a PR with the above fix - https://github.com/doczjs/docz/pull/1696

**Comment by renatobenks** [comment] 2022-02-03 01:52
great work @nicolo-ribaudo, we're going to merge and release it as soon as we can

**Closed** 2022-02-07 05:10 UTC
